* Hello!

I tend to get interested in various projects, but not have a lot of time to put into them. Mainly due to other projects that seems more interesting at the moment or miscellaneous project that are supposed to support the various other projects. Anyway. These are the ones I tend to think about and work on when I have the time.

I have a [[https://oelrich.github.io/oelrich-cv/][CV]] that currently is in swedish only.

** Semi-Active projects

#+BEGIN_QUOTE
These are a few of my favourite things!
#+END_QUOTE

*** [[https://github.com/oelrich/clp][Constraint Logic Programming]]

We shouldn't have to write our own code, like animals. We should state intent and have the computer write the code for us. That's the idea anyway. In practice this project hasn't progressed that far, but it is a fun domain to consider and explore.

*** [[https://github.com/oelrich/yggdrasil][RISC-V Exploration]]

Poking around in a virtual RISC-V chip. It's quite enjoyable, would highly recommend!

*** [[https://github.com/oelrich/yeast-so-you-know][Microscopy and other -scopys]]

A simple server to publish images from a camera endowed Raspberry Pi.
